#!/usr/bin/env perl
use v5.26;
use strict;

use lib qw(lib);
use Local::CPANSA qw(:cpan :reports);

my $template = "%2d %10s %10s %12d %s\n";

foreach my $file ( get_all_reports()->@* ) {
	say STDERR "Processing <$file>";
	my $data = 	load_report($file);

	my $unfixed = grep { ! defined $_->{fixed_versions} or $_->{fixed_versions}->@* == 0 } $data->{advisories}->@*;

	my $latest_on_cpan = latest_on_cpan( $data->{distribution} );
	next unless defined $latest_on_cpan; # some things disappear

	# if there are no reports that are outstanding, update the checked info
	# and move on
	if( $unfixed == 0 ) {
		$data->{last_checked} = time;
		$data->{latest_version} = $latest_on_cpan;
		save_report($file, $data);
		next;
		}

	# if there are outstanding reports, but we've already checked the latest version
	# then there is nothing for use to do
	next if $data->{latest_version} eq $latest_on_cpan;

	printf $template,
		$unfixed,
		$data->{'latest_version'},
		$latest_on_cpan,
		$data->{'last_checked'},
		$data->{'url'} // $file;
	}
