#!/Users/brian/bin/perl
use v5.26;
use utf8;
use open qw(:std :utf8);
use experimental qw(signatures);

use FindBin;
use lib "$FindBin::Bin/../lib";

use Local::CPANSA;

use Mojo::Util qw(dumper);

=head1 NAME

make_feed - turn the CVE search results into RSS

=head1 SYNOPSIS

	% perl util/make_feed

=head1 DESCRIPTION

B<make_feed> grabs some search results and turns those into items in
an RSS feed. This way, interested people can track new results that
we should add to the database.

If there are no new results for a day, this adds an item in the RSS
to note that there was nothing new. That we, we notice that it's still
running.

=cut

my $opts = {
	owner => $ENV{CPANSA_OWNER} // Local::CPANSA::default_github_owner(),
	repo  => $ENV{CPANSA_REPO}  // Local::CPANSA::default_github_repo(),
	};

foreach my $cve ( get_unevaluated_cve()->@* ) {
	next if github_cve_issue_exists( [$cve], $opts );
	add_issue( $cve );
	}

sub now { # 2003-12-13T18:30:02Z
	my @gmtime = gmtime();
	$gmtime[5] += 1900;
	$gmtime[4] += 1;

	my $now = sprintf '%4d-%02d-%02dT%02d:%02d:%02dZ', @gmtime[5,4,3,2,1,0];
	}
