---
name: cpan-audit

# https://github.com/actions/checkout/issues/1590
env:
    ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
    cancel-in-progress: true

on:
    push:
        branches:
            - '**'
            - '!**appveyor**'
            - '!**circleci**'
            - '!**macos**'
            - '!**notest**'
            - '!**release**'
            - '!**windows**'
        tags-ignore:
            # I tag release pushes but those should have already been tested
            - 'release-*'
        paths-ignore:
            # list all the files which are irrelevant to the tests
            # non-code, support files, docs, etc
            - '.appveyor.yml'
            - '.circleci'
            - '.gitattributes'
            - '.github/workflows/linux.yml'
            - '.github/workflows/release.yml'
            - '.github/workflows/windows.yml'
            - '.github/workflows/macos.yml'
            - '.github/workflows/prove.yml'
            - '.github/workflows/validate.yml'
            - '.github/workflows/gpg_signatures.yml'
            - '.gitignore'
            - '.releaserc'
            - 'Changes'
            - 'LICENSE'
            - 'README.pod'
            - 'README.md'
            - 'SECURITY.md'
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: "37 3 * * 0"
jobs:
    perl:
        environment: automated_testing
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                perl-version:
                    - '5.26-buster'
                    - '5.28-buster'
                    - '5.30-bullseye'
                    - '5.32-bullseye'
                    - '5.34-bullseye'
                    - '5.36-bookworm'
                    - '5.38-bookworm'
                    - 'latest'
        container:
            image: perl:${{ matrix.perl-version }}
        steps:
            - uses: actions/checkout@v3
            - name: setup platform
              run: |
                apt-get -y update
                apt-get -y upgrade
                apt-get -y install \
                    curl \
                    jq \
                    ${{ vars.UBUNTU_EXTRA_APT_GET }}

                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg --output /usr/share/keyrings/githubcli-archive-keyring.gpg
                chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                apt update
                apt-get -y install gh

                git config --global --add safe.directory $(pwd)
            - name: show setup
              run: |
                which git
                pwd
                git config --global --add safe.directory /__w/cpan-security-advisory/cpan-security-advisory
                git rev-parse HEAD
                git remote show
                git config --get remote.origin.url
            - name: Load cache
              id: perl-modules-cache-restore
              uses: actions/cache/restore@v4
              with:
                key: cpan-audit-${{ runner.os }}-${{ matrix.perl-version }}-modules
                path: |
                  /usr/local/lib/perl5
                  /usr/local/bin/cover
                  /usr/local/bin/cpan
            - name: Delete cache
              id: delete-cache
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/actions/caches \
                  | jq -r '.actions_caches[] | select(.key == "${{ steps.perl-modules-cache-restore.outputs.cache-primary-key }}") | .id' \
                  | xargs -I{} gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/actions/caches/{}
            - name: update toolchain
              run: |
                cpan App::Cpan
                cpan -v
            - name: install local dependencies
              run: |
                cpan -T -M http://www.cpan.org Antsy CPAN::DistnameInfo Data::Rx HTTP::Tiny JSON MetaCPAN::Client Module::CoreList Mojo::Util Mojo::File Mojo::JSON PerlIO::gzip Ref::Util YAML::Tiny YAML::XS || true
            - name: install latest
              run: |
                cpan -T -M http://www.cpan.org .
                perl util/generate
                cpan .
            - name: Run tests
              run: |
                perl Makefile.PL
                make test
                prove -r -b xt
            - name: check CPAN::Audit
              run: |
                cpan -M http://www.cpan.org CPAN::Audit
            - name: Save cache
              id: perl-modules-cache-save
              uses: actions/cache/save@v4
              if: always()
              with:
                key: ${{ steps.perl-modules-cache-restore.outputs.cache-primary-key }}
                path: |
                  /usr/local/lib/perl5
                  /usr/local/bin/cover
                  /usr/local/bin/cpan
