---
name: generate-db

# https://github.com/actions/checkout/issues/1590
env:
    ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

permissions:
    contents: write
    id-token: write
    attestations: write

on:
    push:
    workflow_dispatch:

jobs:
    generate:
# We need a GitHub secret, so create an Environment named "release"
# * Go to Settings > Environment (repo settings, not account settings)
# * Make an environment named "release"
# * Add a secret named "RELEASE_ACTION_TOKEN" with a GitHub token with repo permissions
# If you use a different token name, update "RELEASE_ACTION_TOKEN" in the last
# step in this job.
        environment: generate
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                perl-version:
                    - 'latest'
        container:
            image: perl:${{ matrix.perl-version }}
        steps:
            - uses: actions/checkout@v3
            - name: git corrections
              run: |
                git config --global --add safe.directory `pwd`
# Some older versions of Perl have trouble with hostnames in certs. I
# haven't figured out why.
            - name: Setup environment
              run: |
                echo "PERL_LWP_SSL_VERIFY_HOSTNAME=0" >> $GITHUB_ENV
# Restore the last module installation for this OS/perl combination. This
# saves several minutes in some cases. When cpan installs updates, the
# 'save' counterpart for 'restore' will update the cache.
            - name: Restore Perl modules
              id: perl-modules-cache-restore
              uses: actions/cache/restore@v4
              with:
                key: generate-${{ runner.os }}-${{ matrix.perl-version }}-modules
                path: |
                  /usr/local/lib/perl5
                  /usr/local/bin/cover
                  /usr/local/bin/cpan
# We cannot reuse cache keys, so we'll delete it and then save it again
# There are various hacks for this, but GitHub has so far declined to
# do what so many people want. This seems like a long way to go to do
# this, but most of the problem is translating the unique cache key name
# to another hidden ID value. This is pervasive in the GitHub API.
            - name: Delete cache
              id: delete-cache
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/actions/caches \
                  | jq -r '.actions_caches[] | select(.key == "${{ steps.perl-modules-cache-restore.outputs.cache-primary-key }}") | .id' \
                  | xargs -I{} gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/actions/caches/{}
# I had some problems with openssl on Ubuntu, so I punted by installing
# cpanm first, which is easy. I can install IO::Socket::SSL with that,
# then switch back to cpan. I didn't explore this further, but what you
# see here hasn't caused problems for me.
#
# Need HTTP::Tiny 0.055 or later. Probably don't need it at all since I'm
# not using cpan here.
#
# Test::Manifest is there because it's a thing I do. If you are writing
# modules and don't know what it is, you don't need it.
            - name: Install cpanm and multiple modules
              run: |
                curl -L https://cpanmin.us | perl - App::cpanminus
                cpanm --notest IO::Socket::SSL HTTP::Tiny ExtUtils::MakeMaker Test::Manifest ${{ vars.EXTRA_CPANM_MODULES }}
                cpan -M http://www.cpan.org -T Test::Manifest ${{ vars.EXTRA_CPAN_MODULES }}
# Install the dependencies, again not testing them. This installs the
# module in the current directory, so we end up installing the module,
# but that's not a big deal.
            - name: Install dependencies
              run: |
                cpanm --notest --installdeps --with-suggests --with-recommends .
            - name: generate
              run: |
                perl util/generate > /dev/null
                git status
# Now always save the Perl modules in case we updated some versions
            - name: Save Perl modules
              id: perl-modules-cache-save
              uses: actions/cache/save@v4
              if: always()
              with:
                key: ${{ steps.perl-modules-cache-restore.outputs.cache-primary-key }}
                path: |
                  /usr/local/lib/perl5
                  /usr/local/bin/cover
                  /usr/local/bin/cpan
